### ISSUE TITLE
will not working...

### ISSUE THREAD

**Issue by matzZz** [jasoncodes/homebridge-bluetooth-tag#1]
Hi, I need your help.

_[iTag1]_ Initializing Bluetooth Tag accessory...
module.js:472
    throw err;
    ^

Error: Cannot find module 'bluetooth-hci-socket'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-bluetooth-tag/node_modules/noble/lib/hci-socket/hci.js:6:26)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)_

**Comment by jeffl78** [comment]
I’m having the same issue

**Comment by jasoncodes** [comment]
It sounds like the noble library does not have its native extensions installed correctly. I would:
* first ensure you have the appropriate dependencies installed (`sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev` on Raspberian, see https://github.com/noble/noble),
* `rm -rf /usr/lib/node_modules/homebridge-bluetooth-tag/node_modules/noble`, and then
* re-run `npm install` or `yarn` (depending on which Node package manager you are using).

**Comment by jeffl78** [comment]
I got mine working, the file path was different than discribed in the read me file for the project I was working on.  I opened an issue, I’ll post a link. 

https://github.com/emmcc/node-switchmate/issues/11
